mysql:
  image: mysql:latest
  environment:
    - MYSQL_ROOT_PASSWORD=tuneefy
    - MYSQL_DATABASE=tuneefy
    - MYSQL_USER=tuneefy
    - MYSQL_PASSWORD=tuneefy
  ports:
    - "3306:3306"
hhvm:
  image: hhvm:latest
  volumes:
    - .:/var/www/tuneefy
  ports:
    - "9000:9000"
  links:
    - mysql
nginx:
  image: nginx:latest
  volumes:
    - .:/var/www/tuneefy
  links:
    - hhvm
  ports:
    - "80:80"
